### ISSUE TITLE
Engine flicker of ships without trails

### ISSUE THREAD

**Issue by rbrune** [GardensOfKadesh/Homeworld#11]
E.g. in the opening sequence the motherships engine flickers while it is still supposed to be off.
Compare with this recording of the opening sequence: https://youtu.be/1pAK767FfvE?t=304

**Comment by spartanatreyu** [comment]
If I recall correctly, I think the original game had a flickering engine depending on the renderer chosen.

Could be a bug from before the port...

**Comment by rbrune** [comment]
Hi,
thank you for the input.
We mainly work on this gitlab repository at the moment: https://gitlab.com/homeworldsdl/TenhauserGate

From time to time I pull the changes but especially issues are handled over there and on discord.

Speaking of engine flicker. I fixed this in the tenhauser version. If I remember correctly it was a kind of floating point precision issue. E.g. velocity == 0 -> no engine effect, velocity != 0 -> engine glow effect. And due to physics sim precision issues the values switched back and forth between equal and unequal zero.
