### ISSUE TITLE
Advance Support Frigate doesn't work

### ISSUE THREAD

**Issue by fireice-uk** [GardensOfKadesh/Homeworld#20]
Am I being stupid here? Healing icon shows but if I left click, nothing happens.

Dragging a box similarly does nothing

**Comment by fireice-uk** [comment]
Possibly same bug: When trying to dock with mothership specifically, similarly, left click only selects it

**Comment by ThibaultLemaire** [comment]
You're not being stupid, just a victim of the design quirks of an old user interface. You have to hold "special" for healing (I believe it's Z by default), and D for docking I think.
